# Generated by Django 4.2.2 on 2023-07-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_sizes_remove_product_sizes_product_sizes'),
        ('order', '0006_remove_order_products_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products_order', to='products.product'),
        ),
    ]
