# Generated by Django 4.2.2 on 2023-07-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_sizes_remove_product_sizes_product_sizes'),
        ('order', '0008_remove_order_products_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('address', models.CharField()),
            ],
            bases=('products.product',),
        ),
    ]
