# Generated by Django 4.2.2 on 2023-06-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='desc',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
