# Generated by Django 4.2.2 on 2023-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_image_category_image_url_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='original_image_url',
            field=models.URLField(blank=True, max_length=2220000, null=True),
        ),
    ]
