# Generated by Django 4.2.2 on 2023-07-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_images_url_productimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_currency',
        ),
    ]
