# Generated by Django 4.2.2 on 2023-07-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_price_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
