# Generated by Django 4.2.2 on 2023-07-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(default=1, max_length=2220000),
            preserve_default=False,
        ),
    ]
